---

require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6
  NewCops: enable

### METRICS ###
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - mongoid-enum-dazzl.gemspec
Metrics/MethodLength:
  Exclude:
    - lib/mongoid/enum/dazzl.rb

### NAMINGS ###
Naming/HeredocDelimiterNaming:
  Enabled: false

### LAYOUTS ###
Layout/LineLength:
  Max: 80
  Exclude:
    - spec/**/*

### STYLES ###
Style/Documentation:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false

### RSPEC ###
RSpec/MultipleMemoizedHelpers:
  Max: 6
RSpec/NestedGroups:
  Max: 5
RSpec/IdenticalEqualityAssertion:
  Exclude:
    - spec/mongoid/enum/dazzl_spec.rb
